-- Add detailed property characteristics

-- House features
ALTER TABLE properties ADD COLUMN IF NOT EXISTS floor INTEGER;
ALTER TABLE properties ADD COLUMN IF NOT EXISTS total_floors INTEGER;
ALTER TABLE properties ADD COLUMN IF NOT EXISTS furnished BOOLEAN DEFAULT FALSE;
ALTER TABLE properties ADD COLUMN IF NOT EXISTS renovation VARCHAR(20);
ALTER TABLE properties ADD COLUMN IF NOT EXISTS balcony BOOLEAN DEFAULT FALSE;
ALTER TABLE properties ADD COLUMN IF NOT EXISTS parking BOOLEAN DEFAULT FALSE;
ALTER TABLE properties ADD COLUMN IF NOT EXISTS wifi BOOLEAN DEFAULT FALSE;
ALTER TABLE properties ADD COLUMN IF NOT EXISTS washer BOOLEAN DEFAULT FALSE;
ALTER TABLE properties ADD COLUMN IF NOT EXISTS conditioner BOOLEAN DEFAULT FALSE;
ALTER TABLE properties ADD COLUMN IF NOT EXISTS fridge BOOLEAN DEFAULT FALSE;
ALTER TABLE properties ADD COLUMN IF NOT EXISTS tv BOOLEAN DEFAULT FALSE;

-- Car features
ALTER TABLE properties ADD COLUMN IF NOT EXISTS car_brand VARCHAR(100);
ALTER TABLE properties ADD COLUMN IF NOT EXISTS car_year INTEGER;
ALTER TABLE properties ADD COLUMN IF NOT EXISTS car_transmission VARCHAR(20);
ALTER TABLE properties ADD COLUMN IF NOT EXISTS car_fuel VARCHAR(20);
ALTER TABLE properties ADD COLUMN IF NOT EXISTS car_mileage INTEGER;
ALTER TABLE properties ADD COLUMN IF NOT EXISTS car_color VARCHAR(50);
ALTER TABLE properties ADD COLUMN IF NOT EXISTS car_ac BOOLEAN DEFAULT FALSE;
ALTER TABLE properties ADD COLUMN IF NOT EXISTS car_seats INTEGER;
